import { SESv2Client, SendEmailCommand } from "@aws-sdk/client-sesv2";
import { marked } from "marked";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EmailConfig {
  /** Enable email notifications for scheduled job completions */
  enabled?: boolean;
  /** From address (e.g., "MCP-AskSQL <noreply@yourdomain.com>") */
  from: string;
  /** AWS SES config */
  ses?: {
    region?: string;
    accessKeyId?: string;
    secretAccessKey?: string;
  };
}

// ---------------------------------------------------------------------------
// Email Service — AWS SES direct (same pattern as MyHeadlines)
// ---------------------------------------------------------------------------

export class EmailService {
  private config: EmailConfig;
  private sesClient: SESv2Client;

  constructor(config: EmailConfig) {
    this.config = config;

    if (config.ses?.accessKeyId && !config.ses?.secretAccessKey) {
      throw new Error("Email config: ses.secretAccessKey is required when ses.accessKeyId is provided");
    }

    this.sesClient = new SESv2Client({
      region: config.ses?.region ?? "us-east-1",
      credentials: config.ses?.accessKeyId
        ? { accessKeyId: config.ses.accessKeyId, secretAccessKey: config.ses.secretAccessKey ?? "" }
        : undefined,
    });
  }

  /**
   * Send a scheduled job report email with the markdown summary as HTML body
   * and an optional PDF attachment.
   */
  async sendReport(opts: {
    jobName: string;
    recipients: string[];
    markdown: string;
    pdfBuffer?: Buffer;
  }): Promise<boolean> {
    const { jobName, recipients, markdown, pdfBuffer } = opts;

    if (recipients.length === 0) return false;

    const dateStr = new Date().toLocaleDateString("en-US", {
      weekday: "long", year: "numeric", month: "long", day: "numeric",
    });

    const subject = `${jobName} — Scheduled Report — ${dateStr}`;
    const htmlBody = await marked.parse(markdown);

    const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; color: #1a1a2e; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #16213e, #0f3460); padding: 20px 24px; border-radius: 8px 8px 0 0;">
    <h1 style="margin: 0; color: #fff; font-size: 18px;">MCP-AskSQL Scheduled Report</h1>
    <p style="margin: 4px 0 0; color: #94a3b8; font-size: 13px;">${jobName} — ${dateStr}</p>
  </div>
  <div style="border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px; padding: 24px;">
    ${htmlBody}
  </div>
  <div style="text-align: center; padding: 16px; color: #94a3b8; font-size: 11px;">
    Generated by MCP-AskSQL Scheduler
  </div>
</body>
</html>`;

    try {
      if (pdfBuffer) {
        // Send as raw MIME email with PDF attachment
        const rawEmail = this.buildRawEmail(recipients, subject, html, jobName, pdfBuffer);
        await this.sesClient.send(new SendEmailCommand({
          FromEmailAddress: this.config.from,
          Destination: { ToAddresses: recipients },
          Content: { Raw: { Data: rawEmail } },
        }));
      } else {
        // Simple email without attachment
        await this.sesClient.send(new SendEmailCommand({
          FromEmailAddress: this.config.from,
          Destination: { ToAddresses: recipients },
          Content: {
            Simple: {
              Subject: { Data: subject, Charset: "UTF-8" },
              Body: {
                Html: { Data: html, Charset: "UTF-8" },
                Text: { Data: markdown, Charset: "UTF-8" },
              },
            },
          },
        }));
      }

      console.error(`[email] Report sent to ${recipients.join("; ")} for job "${jobName}"`);
      return true;
    } catch (err) {
      console.error(`[email] Failed to send report for job "${jobName}":`, err instanceof Error ? err.message : err);
      return false;
    }
  }

  /** Build a raw MIME email with HTML body + PDF attachment. */
  private buildRawEmail(recipients: string[], subject: string, html: string, jobName: string, pdfBuffer: Buffer): Uint8Array {
    const boundary = `----=_Part_${Date.now()}_${Math.random().toString(36).slice(2)}`;
    const safeJobName = jobName.replace(/[^a-zA-Z0-9_-]/g, "_");
    const filename = `${safeJobName}_${new Date().toISOString().slice(0, 10)}.pdf`;

    const rawMessage = [
      `From: ${this.config.from}`,
      `To: ${recipients.join(", ")}`,
      `Subject: ${subject}`,
      `MIME-Version: 1.0`,
      `Content-Type: multipart/mixed; boundary="${boundary}"`,
      ``,
      `--${boundary}`,
      `Content-Type: text/html; charset=UTF-8`,
      `Content-Transfer-Encoding: 7bit`,
      ``,
      html,
      ``,
      `--${boundary}`,
      `Content-Type: application/pdf; name="${filename}"`,
      `Content-Transfer-Encoding: base64`,
      `Content-Disposition: attachment; filename="${filename}"`,
      ``,
      pdfBuffer.toString("base64"),
      ``,
      `--${boundary}--`,
    ].join("\r\n");

    return new TextEncoder().encode(rawMessage);
  }
}
