import nodemailer from "nodemailer";
import type { Transporter } from "nodemailer";
import { marked } from "marked";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EmailConfig {
  /** Enable email notifications for scheduled job completions */
  enabled?: boolean;
  /** From address (e.g., "MCP-AskSQL <you@gmail.com>") */
  from: string;
  /** SMTP config (works with Gmail, Outlook, or any SMTP provider) */
  smtp: {
    host: string;
    port?: number;
    secure?: boolean;
    user: string;
    pass: string;
  };
}

// ---------------------------------------------------------------------------
// Email Service — nodemailer SMTP (same pattern as dataflow_360_claude)
// ---------------------------------------------------------------------------

export class EmailService {
  private config: EmailConfig;
  private transporter: Transporter;

  constructor(config: EmailConfig) {
    this.config = config;

    if (!config.smtp?.host || !config.smtp?.user || !config.smtp?.pass) {
      throw new Error("Email config: smtp.host, smtp.user, and smtp.pass are required");
    }

    this.transporter = nodemailer.createTransport({
      host: config.smtp.host,
      port: config.smtp.port ?? 587,
      secure: config.smtp.secure ?? (config.smtp.port === 465),
      auth: { user: config.smtp.user, pass: config.smtp.pass },
    });
  }

  /**
   * Send a scheduled job report email with the markdown summary as HTML body
   * and an optional PDF attachment.
   */
  async sendReport(opts: {
    jobName: string;
    recipients: string[];
    markdown: string;
    pdfBuffer?: Buffer;
  }): Promise<boolean> {
    const { jobName, recipients, markdown, pdfBuffer } = opts;

    if (recipients.length === 0) return false;

    const dateStr = new Date().toLocaleDateString("en-US", {
      weekday: "long", year: "numeric", month: "long", day: "numeric",
    });

    const subject = `${jobName} — Scheduled Report — ${dateStr}`;
    const htmlBody = await marked.parse(markdown);

    const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; color: #1a1a2e; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #16213e, #0f3460); padding: 20px 24px; border-radius: 8px 8px 0 0;">
    <h1 style="margin: 0; color: #fff; font-size: 18px;">MCP-AskSQL Scheduled Report</h1>
    <p style="margin: 4px 0 0; color: #94a3b8; font-size: 13px;">${jobName} — ${dateStr}</p>
  </div>
  <div style="border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px; padding: 24px;">
    ${htmlBody}
  </div>
  <div style="text-align: center; padding: 16px; color: #94a3b8; font-size: 11px;">
    Generated by MCP-AskSQL Scheduler
  </div>
</body>
</html>`;

    const attachments: Array<{ filename: string; content: Buffer; contentType: string }> = [];
    if (pdfBuffer) {
      const safeJobName = jobName.replace(/[^a-zA-Z0-9_-]/g, "_");
      attachments.push({
        filename: `${safeJobName}_${new Date().toISOString().slice(0, 10)}.pdf`,
        content: pdfBuffer,
        contentType: "application/pdf",
      });
    }

    try {
      await this.transporter.sendMail({
        from: this.config.from,
        to: recipients.join(", "),
        subject,
        html,
        attachments,
      });
      console.error(`[email] Report sent to ${recipients.join("; ")} for job "${jobName}"`);
      return true;
    } catch (err) {
      console.error(`[email] Failed to send report for job "${jobName}":`, err instanceof Error ? err.message : err);
      return false;
    }
  }
}
